### ISSUE TITLE
Setup routing in existing map

### ISSUE THREAD

**Issue by arcontechnologies** [skedgo/tripkit-leaflet#3]
Hi,

I'm newbie in JavaScript and Leaflet as well. From what I understand, the demo example initialize routing in a new map. In my case I have already setup a map with some features and at certain point of time I want to let the user trigger the routing functionality. When using the code as it is, I'm ending up with JavaScript error message : map is already initialized. 

Any help on this will be appreciate.

**Comment by rangermix** [comment]
Hi,

You said you were "using the code as it is", did you happen to copy and paste the code both in Plugin StartUp -> default config & Initialize Options? Note that there's also this line of code `L.tripgoRouting.mapLayer.initialize(options);` at the end of Initialize Options codes. If that's not the case, could you please share your code for further diagnosis?

**Comment by arcontechnologies** [comment]
Hi,

No, my code is encapsulated in init function that is called when the html page is rendered. the only moment I'm calling "initialize" is at the end of my function.

Actually my code looks like this :

```
export function initMap(latitude, longitude) {

    var mymap = L.map('mapid').setView([latitude, longitude], 15);

    L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token={accessToken}', {
        attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
        maxZoom: 18,
        id: 'mapbox/streets-v11',
        tileSize: 512,
        zoomOffset: -1,
        accessToken: 'My MapBox Token'
    }).addTo(mymap);
	
	var options = {
        "mapId": "mapidr",
        "googleTile": false,
        "marCenter": {
            "lat": latitude,
            "lng": longitude
        },
        "floatPanel": true,
        "tripgoApiKey": "My TripGo Token"
    }
    L.tripgoRouting.mapLayer.initialize(options);	
}
```
When running my code, I'm getting the error : Map already initialized. I wonder what I'm doing wrong in my code.

kr,

**Comment by rangermix** [comment]
Ahh sry I was misunderstanding your question. This is probably because you have called `L.map()` twice, see [this issue from the Leaflet repo](https://github.com/Leaflet/Leaflet/issues/7208) and [another issue related to React](https://github.com/Leaflet/Leaflet/issues/3962#issuecomment-384510881).

**Comment by gimenna** [comment]
Hi, 

yes, the issue is that you are initializing the map twice. 
Those instructions are initializing the map:
`var mymap = L.map('mapid').setView([latitude, longitude], 15);`
`L.tripgoRouting.mapLayer.initialize(options);`

You  should first initialize the map using our code and then get it to add your config. Something like this:

```
var options = {
        "mapId": "mapid",
        "googleTile": false,
        "marCenter": {
            "lat": 51.511011,
            "lng": -0.125448
        },
        "floatPanel": true,
        "tripgoApiKey": "My TripGo Token"
    }
    L.tripgoRouting.mapLayer.initialize(options);

    var mymap = L.tripgoRouting.mapLayer.getMap();
    L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token={accessToken}', {
        attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
        maxZoom: 18,
        id: 'mapbox/streets-v11',
        tileSize: 512,
        zoomOffset: -1,
        accessToken: 'My MapBox Token'
    }).addTo(mymap);

```

Also check in your code that you named the map as "mapid" and then in  options you set "mapidr"
Hope it helps!

**Comment by arcontechnologies** [comment]
Thanks. it works !
